# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
#DB Management
#lisqlme@gmail.com
#lisqlmeadmin
#
#    url: jdbc:mysql://localhost:3306/lime?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
#    username: Admin
#    password: Admin
#    url: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11209663?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
#    username: sql11209663
#    password: kan4wNnVVj

spring:
  datasource:
    url: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11209663?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: sql11209663
    password: kan4wNnVVj
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3
  credentials:
    resource-id: oauth2-resource
    client-id: test-lime-client
    secret: 8c0ae96c-dc07-11e7-9296-cec278b6b50a