# ===============================
# = JPA / HIBERNATE
# ===============================
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-50-19-126-219.compute-1.amazonaws.com:5432/dlvk4k4kg58ni
    username: zdtcqbmjxerpqi
    password: 42a288f038279f2c0f5ab3db025612f65c74d582101934f3aecf9fc7992a9db9
    driverClassName: org.postgresql.Driver