# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
#DB Management
#lisqlme@gmail.com
#lisqlmeadmin

spring:
  datasource:
    url: mysql://b7b40aab110c35:0ddc09e5@us-cdbr-iron-east-05.cleardb.net/heroku_cd26d1e63353c07?reconnect=true
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
    port: 8080
    address: localhost
    session:
      timeout: 120