# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
#DB Management
#lisqlme@gmail.com
#lisqlmeadmin

spring:
  datasource:

#    url: jdbc:mysql://localhost:3306/lime?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
#    username: limeadmin
#    password: LIMEadmin12#$
    url: jdbc:mysql://localhost:3306/lime?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: test
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
    port: 8080
    address: localhost
    session:
      timeout: 720
storage:
  properties:
    location: pics