# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
#DB Management
#lisqlme@gmail.com
#lisqlmeadmin

spring:
  datasource:

#    url: jdbc:mysql://localhost:3306/lime?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
#    username: limeadmin
#    password: LIMEadmin12#$
    url: jdbc:mysql://localhost:3306/lime?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: test
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/lime
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver
