# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
# push command: git push heroku LimeAppHeroku:master
# heroku credentials:
#   username:limemini102@gmail.com
#   password:LIMEmini102!@
# gmail password: limeminipassword
spring:
  datasource:
    url: jdbc:mysql://b7b40aab110c35:0ddc09e5@us-cdbr-iron-east-05.cleardb.net/heroku_cd26d1e63353c07?reconnect=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
    session:
      timeout: 720
storage:
  properties:
    location: pics