# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
# push command: git push heroku LimeAppHeroku:master
# heroku credentials:รณ
#   username:limemini102@gmail.com
#   password:LIMEmini102!@
# gmail password: limeminipassword
spring:
  datasource:
    url: jdbc:mysql://b3e56c4ac330ab:a3462a44@us-cdbr-iron-east-05.cleardb.net/heroku_8bd1755ae2a2862?reconnect=true&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis
server:
  session:
    timeout: 25920000
storage:
  properties:
    location: pics